// OpenGL 2.1 compatibility profile bindings, generated by gl_generator.
#![allow(
    clippy::all,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused
)]

include!(concat!(env!("OUT_DIR"), "/gl_bindings.rs"));
