//! Static menu screen definitions — decoded from V2000.EXE.
//!
//! The original menu engine walks static screen records in `.data`/`.rdata`
//! (see `docs/re/MENU_SYSTEM.md` §Layer 3). Those records were
//! extracted to `crates/v2k-game/data/menu_tree.json` by a private EXE
//! analysis script (34 screens) and are embedded here verbatim;
//! this module parses them into typed definitions:
//!
//! - item draw callbacks → [`DrawKind`] (text / 3-D prop / setting rows)
//! - item select callbacks → [`SelectAction`] (open submenu / spinner /
//!   back / start game / cheat / …)
//! - settings dword addresses (base 0x4CB3D8) → [`SettingId`]
//!
//! String ids are GLOBAL pool ids (cumulative Section 2 of system levels
//! 2-5, runtime array DAT_004FE628); model ids likewise (levels 2/3/5,
//! DAT_004FE640) — resolve via `ResourceCache::global_string` /
//! `global_model`. The JSON also carries pre-resolved `label` fallbacks.

use std::collections::HashMap;

use serde::Deserialize;

/// The extracted screen tree, embedded at compile time. Source of truth:
/// `crates/v2k-game/data/menu_tree.json`, regenerated by the private EXE
/// analysis tooling.
const MENU_TREE_JSON: &str = include_str!("../data/menu_tree.json");

// ── Well-known screen addresses ─────────────────────────────────────────────

/// Main menu prop ring (7 items, flags 0xC4). Registered at menu init by
/// FUN_0042B230.
pub const MAIN_RING: u32 = 0x4C0CF8;
/// Display settings (Rendering/Resolution/Bilinear/Display/Camera/Targetter).
pub const DISPLAY: u32 = 0x4C14D0;
/// Sound settings (Sound, Ambient).
pub const SOUNDS: u32 = 0x4C12F0;
/// Control settings (Absolute Mode/Sensitivity/Joystick/Self Righting).
pub const CONTROLS: u32 = 0x4C13D0;
/// Network session screen (multipc prop target).
pub const NETWORK: u32 = 0x4C11D0;
/// Save/load entry screen ("Accessing Memory Card", slopt prop target).
pub const MEMCARD_ACCESS: u32 = 0x4C1740;
/// Occupied-save confirmation ("Overwrite game?", Yes/No).
pub const SAVE_OVERWRITE_CONFIRM: u32 = 0x4C1598;
/// Save operation screen ("Saving game").
pub const SAVE_PROGRESS: u32 = 0x4C17B0;
/// Successful-save acknowledgement ("Game Saved").
pub const SAVE_SUCCEEDED: u32 = 0x4C1820;
/// Save/load failure acknowledgement ("Access Failed").
pub const SAVE_ACCESS_FAILED: u32 = 0x4C1890;
/// In-game Options (Display/Sounds/Controls).
pub const OPTIONS_INGAME: u32 = 0x4C1260;
/// Pause menu, simple variant.
pub const PAUSE_SIMPLE: u32 = 0x4D1090;
/// Pause menu, full variant (Continue/Options/Briefing/Status/Replay/Cheats/Quit).
pub const PAUSE_FULL: u32 = 0x4D1190;
/// Quit confirmation dialog (Yes/No).
pub const QUIT_CONFIRM: u32 = 0x4C4DD0;
/// Cheats menu.
pub const CHEATS: u32 = 0x4D0FE8;

/// Settings struct base address in .data (registry-backed, accessor
/// FUN_0043C7C0).
pub const SETTINGS_BASE: u32 = 0x4CB3D8;

// ── Visibility mask bits (FUN_0043CBA0) ─────────────────────────────────────
//
// An item is shown when `item.flags & mask != 0` (flags 0 = always hidden).
// The runtime mask is 4 in the frontend; in-game it is 3 (single-player)
// or 1 (DAT_004F741C set), OR'd with 8 when cheats are unlocked.

/// In-game (always while playing).
pub const VIS_INGAME: u32 = 1;
/// In-game, single-player only.
pub const VIS_INGAME_SP: u32 = 2;
/// Frontend menu.
pub const VIS_FRONTEND: u32 = 4;
/// Cheats unlocked.
pub const VIS_CHEATS: u32 = 8;

// ── Typed definitions ───────────────────────────────────────────────────────

/// Identifies a dword in the settings struct at 0x4CB3D8 (offsets per the
/// registry map in MENU_SYSTEM.md plus the bindings observed in the screen
/// records themselves).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SettingId {
    /// +0x00 — sound volume 0-15 (0 = off).
    SoundVolume,
    /// +0x04 — ambient volume 0-15.
    AmbientVolume,
    /// +0x08 — joystick mode (Absolute/Relative).
    Joystick,
    /// +0x10 — display mode index into Section 5.
    Resolution,
    /// +0x14 — renderer (Software/Direct3D).
    Rendering,
    /// +0x18 — bilinear filtering (Disabled/Enabled).
    Bilinear,
    /// +0x1C — display (In a Window / Full Screen).
    FullScreen,
    /// Port extension — Native / preserved 4:3 / legacy Stretched output.
    Scaling,
    /// +0x24 — self righting (Off/Level/Angled).
    SelfRighting,
    /// +0x28 — full analogue / absolute mode.
    AbsoluteMode,
    /// +0x2C — control sensitivity 0-15.
    Sensitivity,
    /// +0x30 — active camera 0-10.
    ActiveCamera,
    /// +0x34 — targetter on/off.
    Targetter,
    /// +0x38 — HUD on/off.
    Hud,
    /// +0x3C — language index.
    Language,
    /// +0x40 — vibration (hidden item in the Controls screen).
    Vibration,
    /// Unmapped settings address.
    Other(u32),
}

impl SettingId {
    /// Map a settings dword address (as stored in item arg2/aux) to its id.
    pub fn from_addr(addr: u32) -> Self {
        match addr.wrapping_sub(SETTINGS_BASE) {
            0x00 => Self::SoundVolume,
            0x04 => Self::AmbientVolume,
            0x08 => Self::Joystick,
            0x10 => Self::Resolution,
            0x14 => Self::Rendering,
            0x18 => Self::Bilinear,
            0x1C => Self::FullScreen,
            0x24 => Self::SelfRighting,
            0x28 => Self::AbsoluteMode,
            0x2C => Self::Sensitivity,
            0x30 => Self::ActiveCamera,
            0x34 => Self::Targetter,
            0x38 => Self::Hud,
            0x3C => Self::Language,
            0x40 => Self::Vibration,
            _ => Self::Other(addr),
        }
    }
}

/// How an item is rendered, classified from its draw callback address.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DrawKind {
    /// Port-owned literal text, independent of the retail string pool.
    PortText { text: &'static str },
    /// FUN_0043B3E0 — plain text, `id` = global string id.
    Text { string_id: u32 },
    /// FUN_0043B410 — 3-D prop, `id` = global model id. `label_id` is the
    /// associated label string (ring items put it in the aux field;
    /// decorative props carry aux = 1, mapped to None here).
    Prop {
        model_id: u32,
        label_id: Option<u32>,
    },
    /// FUN_0043B650 — setting row: label string + value rendered from the
    /// bound setting (value-string convention depends on the setting).
    SettingRow { string_id: u32, setting: SettingId },
    /// FUN_0043B690 — setting row with a direct segmented-bar value. Packed
    /// id: lo16 = label string, hi16 = total bar glyph width.
    SettingRowNumeric {
        string_id: u32,
        value_hint: u32,
        setting: SettingId,
    },
    /// FUN_0043B740 — setting row with named values; value strings follow
    /// the label in the string table (e.g. Sound → Off/On at label+1..).
    SettingRowNamed {
        string_id: u32,
        value_hint: u32,
        setting: SettingId,
    },
    /// FUN_0043B9A0 — save-slot status text (memory-card flow).
    SaveSlotText { string_id: u32 },
    /// FUN_0043BB20 — column/list row text (resolution rows, lobby lists).
    ColumnText { string_id: u32 },
    /// FUN_0043CF30 — dynamic text from a runtime buffer (player name).
    DynamicText,
    /// FUN_0043CEF0 — network session list row.
    NetworkText { string_id: u32 },
    /// FUN_004510C0 / FUN_00452020 — player-status / results rows.
    StatusText { string_id: u32 },
    /// Unclassified draw callback (kept for reference).
    Unknown { addr: u32, string_id: u32 },
}

/// What selecting (or left/right-adjusting) an item does, classified from
/// its select callback address.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SelectAction {
    /// No select callback — not selectable.
    None,
    /// FUN_0043B820 — open submenu (sound 3).
    OpenScreen { target: u32 },
    /// FUN_0042BD60 — main-ring select: prop animation 4 + open submenu.
    RingOpenScreen { target: u32 },
    /// FUN_0042BBF0 — main-ring vehicle prop: start the game.
    StartGame,
    /// FUN_0042D010 — Exit prop: quit to desktop.
    QuitToDesktop,
    /// FUN_0043B850 / FUN_0043B860 — pop the current screen.
    Back,
    /// FUN_0043B7C0 (also 0x43B8C0/0x43CB50 variants with apply hooks) —
    /// spinner: left/right adjusts the bound setting, clamped 0..=max
    /// (sound 1; sound 0 at the limits).
    Spinner { setting: SettingId, max: u32 },
    /// FUN_0043CBF0 — resolution spinner (max = display-mode count - 1,
    /// applies the mode on change).
    ResolutionSpinner,
    /// FUN_0043CC70 / 0x43CCA0 / 0x43CCD0 — 0/1 toggles on a setting.
    Toggle { setting: SettingId },
    /// FUN_00456170 — Continue: resume gameplay (pop the pause stack).
    Continue,
    /// FUN_00456340 — confirmed quit from the pause menu.
    QuitConfirmed,
    /// FUN_00455F50 — grant cheat weapon/item, `code` = 0x3E7xx weapon code.
    Cheat { code: u32 },
    /// FUN_00455FD0/FF0, 0x456020/050 — cheat menu world actions.
    CheatWorld { addr: u32 },
    /// FUN_0043BF30 — save-slot select (memory-card flow).
    SaveSlot,
    /// FUN_0043BFC0 — load-slot select (contains the hidden scancode
    /// easter-egg check, FUN_00496DE0).
    LoadSlot,
    /// FUN_0043CB20 — fire advances the cursor (message screens).
    AdvanceCursor,
    /// FUN_0043CD00 — join network session.
    NetworkJoin,
    /// FUN_0043CEB0 — host network session.
    NetworkHost,
    /// FUN_0043B870 — open the memory-card access flow (save entry).
    OpenMemoryCard,
    /// FUN_0043B8A0 — proceed to the save-progress screen.
    SaveProgress,
    /// FUN_0043B900 — format memory card.
    FormatCard,
    /// Unclassified select callback (kept for reference; treated as no-op).
    Unknown { addr: u32 },
}

/// A menu item, decoded from the 0x1C-byte item record.
#[derive(Debug, Clone)]
pub struct ItemDef {
    /// Visibility mask (vs the VIS_* bits); 0 = always hidden.
    pub visibility: u32,
    /// Static port availability; native rows default to true. The engine
    /// additionally applies any setting-dependent availability rules.
    pub available: bool,
    pub draw: DrawKind,
    pub select: SelectAction,
    /// Raw arg1/arg2 (spinner max / submenu target / weapon code).
    pub arg1: u32,
    pub arg2: u32,
    /// Pre-resolved label from the extractor (fallback when the global
    /// string pool is unavailable).
    pub label: Option<String>,
}

impl ItemDef {
    /// Whether this item is visible under the given mode mask.
    pub fn visible(&self, mask: u32) -> bool {
        self.visibility & mask != 0
    }

    /// Whether the cursor can rest on this item.
    pub fn selectable(&self, mask: u32) -> bool {
        self.visible(mask) && self.select != SelectAction::None
    }
}

/// A decoded row group. `window_rows` is the number of rows simultaneously
/// visible; flag 0x08 enables typewriter reveal and flag 0x10 suppresses the
/// independent re-reveal clock while a row scrolls into the window.
#[derive(Debug, Clone, Copy)]
pub struct RowGroup {
    pub flags: u16,
    pub window_rows: u16,
    pub count: u16,
}

/// A menu screen, decoded from the static screen record.
#[derive(Debug, Clone)]
pub struct ScreenDef {
    /// Record address in the EXE (stable id).
    pub va: u32,
    /// Screen flags (0x100 spinner-row arrows=select, 0x80 up=prev,
    /// 4 wrap, 0xC4 = main ring).
    pub flags: u32,
    pub groups: Vec<RowGroup>,
    pub items: Vec<ItemDef>,
}

impl ScreenDef {
    /// Whether cursor movement wraps around (flags bit 2).
    pub fn wraps(&self) -> bool {
        self.flags & 4 != 0
    }

    /// True for the main prop ring (the only carousel screen).
    pub fn is_ring(&self) -> bool {
        self.va == MAIN_RING
    }
}

// ── Raw JSON model ──────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct RawScreen {
    va: u32,
    flags: u32,
    groups: Vec<RawGroup>,
    items: Vec<RawItem>,
}

#[derive(Deserialize)]
struct RawGroup {
    raw: Vec<u32>,
    count: u32,
}

#[derive(Deserialize)]
struct RawItem {
    flags: u32,
    draw_cb: u32,
    string_id: u32,
    #[serde(default)]
    aux: u32,
    select_cb: u32,
    arg1: u32,
    arg2: u32,
    #[serde(default)]
    label: Option<String>,
}

// ── Classification ──────────────────────────────────────────────────────────

fn classify_draw(it: &RawItem) -> DrawKind {
    let sid = it.string_id;
    match it.draw_cb {
        0x43B3E0 => DrawKind::Text { string_id: sid },
        0x43B410 => DrawKind::Prop {
            model_id: sid,
            // Ring items carry their label string id in aux; decorative
            // props carry aux = 1.
            label_id: if it.aux > 1 { Some(it.aux) } else { None },
        },
        0x43B650 => DrawKind::SettingRow {
            string_id: sid,
            setting: SettingId::from_addr(it.aux),
        },
        0x43B690 => DrawKind::SettingRowNumeric {
            string_id: sid & 0xFFFF,
            value_hint: sid >> 16,
            setting: SettingId::from_addr(it.aux),
        },
        0x43B740 => DrawKind::SettingRowNamed {
            string_id: sid & 0xFFFF,
            value_hint: sid >> 16,
            setting: SettingId::from_addr(it.aux),
        },
        0x43B9A0 => DrawKind::SaveSlotText { string_id: sid },
        0x43BB20 => DrawKind::ColumnText { string_id: sid },
        0x43CF30 => DrawKind::DynamicText,
        0x43CEF0 => DrawKind::NetworkText { string_id: sid },
        0x4510C0 | 0x452020 | 0x450E80 | 0x450EF0 => DrawKind::StatusText { string_id: sid },
        addr => DrawKind::Unknown {
            addr,
            string_id: sid,
        },
    }
}

fn classify_select(it: &RawItem) -> SelectAction {
    match it.select_cb {
        0 => SelectAction::None,
        0x43B820 => SelectAction::OpenScreen { target: it.arg2 },
        0x42BD60 => SelectAction::RingOpenScreen { target: it.arg2 },
        0x42BBF0 => SelectAction::StartGame,
        0x42D010 => SelectAction::QuitToDesktop,
        0x43B850 | 0x43B860 => SelectAction::Back,
        // 0x43B8C0 (sensitivity) and 0x43CB50 (sound volume + palette
        // refresh) are FUN_0043B7C0 spinners with apply hooks.
        0x43B7C0 | 0x43B8C0 | 0x43CB50 => SelectAction::Spinner {
            setting: SettingId::from_addr(it.arg2),
            max: it.arg1,
        },
        0x43CBF0 => SelectAction::ResolutionSpinner,
        0x43CC70 => SelectAction::Toggle {
            setting: SettingId::Rendering,
        },
        0x43CCA0 => SelectAction::Toggle {
            setting: SettingId::Bilinear,
        },
        // FUN_0043CCD0 clamps the Full Screen word to 0..1; the port's
        // Borderless is a third value.
        0x43CCD0 => SelectAction::Spinner {
            setting: SettingId::FullScreen,
            max: 2,
        },
        0x456170 => SelectAction::Continue,
        0x456340 => SelectAction::QuitConfirmed,
        0x455F50 => SelectAction::Cheat { code: it.arg1 },
        0x455FD0 | 0x455FF0 | 0x456020 | 0x456050 => {
            SelectAction::CheatWorld { addr: it.select_cb }
        }
        0x43BF30 => SelectAction::SaveSlot,
        0x43BFC0 => SelectAction::LoadSlot,
        0x43CB20 => SelectAction::AdvanceCursor,
        0x43CD00 => SelectAction::NetworkJoin,
        0x43CEB0 => SelectAction::NetworkHost,
        0x43B870 => SelectAction::OpenMemoryCard,
        0x43B8A0 => SelectAction::SaveProgress,
        0x43B900 => SelectAction::FormatCard,
        addr => SelectAction::Unknown { addr },
    }
}

// ── Tree ────────────────────────────────────────────────────────────────────

/// The full decoded screen tree.
pub struct MenuTree {
    screens: HashMap<u32, ScreenDef>,
}

impl MenuTree {
    /// Parse the embedded screen tree. Panics only on a malformed embedded
    /// JSON, which is a build-time asset error.
    pub fn load() -> Self {
        let raw: HashMap<String, RawScreen> =
            serde_json::from_str(MENU_TREE_JSON).expect("embedded menu_tree.json is valid");

        let mut screens: HashMap<u32, ScreenDef> = raw
            .into_values()
            .map(|rs| {
                let items = rs
                    .items
                    .iter()
                    .map(|it| ItemDef {
                        visibility: it.flags,
                        available: true,
                        draw: classify_draw(it),
                        select: classify_select(it),
                        arg1: it.arg1,
                        arg2: it.arg2,
                        label: it.label.clone().filter(|l| !l.is_empty()),
                    })
                    .collect();
                let groups = rs
                    .groups
                    .iter()
                    .filter(|g| g.count > 0)
                    .map(|g| RowGroup {
                        flags: g.raw.first().copied().unwrap_or(0) as u16,
                        window_rows: g.raw.get(3).copied().unwrap_or(0) as u16,
                        count: g.count as u16,
                    })
                    .collect();
                (
                    rs.va,
                    ScreenDef {
                        va: rs.va,
                        flags: rs.flags,
                        groups,
                        items,
                    },
                )
            })
            .collect();

        // Intentional port extension: expose modern aspect handling without
        // altering the extracted source-of-truth JSON. The first six rows
        // remain the decoded retail Display menu; the port's Scaling row is
        // inserted after Display and before Active Camera, while the
        // decoration prop stays last.
        if let Some(display) = screens.get_mut(&DISPLAY) {
            // Port extension: changing the output and high-tier layout is now
            // supported while paused. Preserve the retail reference JSON.
            for item in &mut display.items {
                if matches!(
                    item.draw,
                    DrawKind::SettingRow {
                        setting: SettingId::Resolution,
                        ..
                    }
                ) {
                    item.visibility |= VIS_INGAME;
                }
            }
            let insert_at = display
                .items
                .iter()
                .position(|item| {
                    matches!(
                        item.draw,
                        DrawKind::SettingRowNumeric {
                            setting: SettingId::ActiveCamera,
                            ..
                        }
                    )
                })
                .unwrap_or(display.items.len());
            display.items.insert(
                insert_at,
                ItemDef {
                    visibility: VIS_INGAME | VIS_FRONTEND,
                    available: true,
                    draw: DrawKind::SettingRow {
                        string_id: u32::MAX,
                        setting: SettingId::Scaling,
                    },
                    select: SelectAction::Spinner {
                        setting: SettingId::Scaling,
                        max: 2,
                    },
                    arg1: 2,
                    arg2: 0,
                    label: Some("Scaling".to_string()),
                },
            );
        }

        // Intentional release policy: multiplayer is not implemented in the
        // port. Replace the runtime session placeholders, keeping the retail
        // screen id, panel and transition route; never edit the reference JSON.
        if let Some(network) = screens.get_mut(&NETWORK) {
            network.items = vec![
                ItemDef {
                    visibility: VIS_FRONTEND,
                    available: false,
                    draw: DrawKind::PortText {
                        text: "Not available yet",
                    },
                    select: SelectAction::None,
                    arg1: 0,
                    arg2: 0,
                    label: None,
                },
                ItemDef {
                    visibility: VIS_FRONTEND,
                    available: true,
                    draw: DrawKind::PortText { text: "Back" },
                    select: SelectAction::Back,
                    arg1: 0,
                    arg2: 0,
                    label: None,
                },
            ];
            network.groups = vec![RowGroup {
                flags: 0x08,
                window_rows: 2,
                count: 2,
            }];
        }

        Self { screens }
    }

    pub fn screen(&self, va: u32) -> Option<&ScreenDef> {
        self.screens.get(&va)
    }

    pub fn len(&self) -> usize {
        self.screens.len()
    }

    pub fn is_empty(&self) -> bool {
        self.screens.is_empty()
    }
}

// ── Unit tests ──────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn tree_loads_all_screens() {
        let tree = MenuTree::load();
        assert!(
            tree.len() >= 34,
            "expected >= 34 screens, got {}",
            tree.len()
        );
        for va in [
            MAIN_RING,
            DISPLAY,
            SOUNDS,
            CONTROLS,
            NETWORK,
            OPTIONS_INGAME,
            PAUSE_SIMPLE,
            PAUSE_FULL,
            QUIT_CONFIRM,
            CHEATS,
            MEMCARD_ACCESS,
        ] {
            assert!(tree.screen(va).is_some(), "missing screen 0x{va:X}");
        }
    }

    #[test]
    fn main_ring_shape() {
        let tree = MenuTree::load();
        let ring = tree.screen(MAIN_RING).unwrap();
        assert!(ring.is_ring());
        assert_eq!(ring.items.len(), 7);
        // Every ring item is a prop with a label.
        for item in &ring.items {
            assert!(matches!(
                item.draw,
                DrawKind::Prop {
                    label_id: Some(_),
                    ..
                }
            ));
        }
        // One StartGame (player4), one QuitToDesktop (optexit), five submenus.
        let starts = ring
            .items
            .iter()
            .filter(|i| i.select == SelectAction::StartGame)
            .count();
        let quits = ring
            .items
            .iter()
            .filter(|i| i.select == SelectAction::QuitToDesktop)
            .count();
        assert_eq!((starts, quits), (1, 1));
        // Ring transitions land on the decoded settings screens.
        let targets: Vec<u32> = ring
            .items
            .iter()
            .filter_map(|i| match i.select {
                SelectAction::RingOpenScreen { target } => Some(target),
                _ => None,
            })
            .collect();
        for t in [DISPLAY, SOUNDS, CONTROLS, NETWORK, MEMCARD_ACCESS] {
            assert!(targets.contains(&t), "ring missing transition to 0x{t:X}");
        }
    }

    #[test]
    fn controls_screen_settings() {
        let tree = MenuTree::load();
        let controls = tree.screen(CONTROLS).unwrap();
        let settings: Vec<SettingId> = controls
            .items
            .iter()
            .filter_map(|i| match i.select {
                SelectAction::Spinner { setting, .. } => Some(setting),
                _ => None,
            })
            .collect();
        for s in [
            SettingId::AbsoluteMode,
            SettingId::Sensitivity,
            SettingId::Joystick,
            SettingId::SelfRighting,
        ] {
            assert!(settings.contains(&s), "controls missing {s:?}");
        }
        // The hidden Vibration item: visibility 0, never shown.
        assert!(controls.items.iter().any(|i| i.visibility == 0));
    }

    #[test]
    fn display_screen_actions() {
        let tree = MenuTree::load();
        let display = tree.screen(DISPLAY).unwrap();
        assert!(display
            .items
            .iter()
            .any(|i| i.select == SelectAction::ResolutionSpinner));
        for s in [SettingId::Rendering, SettingId::Bilinear] {
            assert!(display
                .items
                .iter()
                .any(|i| i.select == SelectAction::Toggle { setting: s }));
        }
        assert!(display.items.iter().any(|i| i.select
            == SelectAction::Spinner {
                setting: SettingId::FullScreen,
                max: 2
            }));
        assert_eq!(
            display.items.len(),
            8,
            "six retail settings, the port Scaling row, and screenop prop"
        );
        let scaling = display
            .items
            .iter()
            .find(|i| {
                i.select
                    == (SelectAction::Spinner {
                        setting: SettingId::Scaling,
                        max: 2,
                    })
            })
            .expect("Display must retain the port scaling selector");
        assert_eq!(scaling.label.as_deref(), Some("Scaling"));
        assert!(scaling.visible(VIS_FRONTEND));
        assert!(scaling.visible(VIS_INGAME));
        let resolution = display
            .items
            .iter()
            .find(|item| {
                matches!(
                    item.draw,
                    DrawKind::SettingRow {
                        setting: SettingId::Resolution,
                        ..
                    }
                )
            })
            .expect("Display must retain its resolution row");
        assert!(resolution.visible(VIS_FRONTEND));
        assert!(resolution.visible(VIS_INGAME));
    }

    #[test]
    fn row_groups_preserve_reveal_flags_and_window_rows() {
        let tree = MenuTree::load();
        let display = tree.screen(DISPLAY).unwrap();
        let rows = display
            .groups
            .iter()
            .find(|group| group.flags & 0x08 != 0)
            .unwrap();
        assert_eq!(rows.flags, 0x08);
        assert_eq!(rows.window_rows, 5);
        assert_eq!(rows.count, 6);

        // 0x4D0EE8 is the retail group that additionally sets flag 0x10:
        // rows use the initial typewriter clock but do not re-type on scroll.
        let no_scroll_reveal = tree.screen(0x4D0EE8).unwrap();
        let rows = no_scroll_reveal
            .groups
            .iter()
            .find(|group| group.flags & 0x08 != 0)
            .unwrap();
        assert_eq!(rows.flags, 0x18);
        assert_eq!(rows.window_rows, 5);
    }

    #[test]
    fn pause_menu_visibility() {
        let tree = MenuTree::load();
        let pause = tree.screen(PAUSE_FULL).unwrap();
        // Continue is visible in-game; Cheats only with the cheat bit.
        let cont = pause
            .items
            .iter()
            .find(|i| i.select == SelectAction::Continue)
            .unwrap();
        assert!(cont.visible(VIS_INGAME));
        let cheats = pause
            .items
            .iter()
            .find(|i| matches!(i.select, SelectAction::OpenScreen { target: CHEATS }))
            .unwrap();
        assert!(!cheats.visible(VIS_INGAME));
        assert!(cheats.visible(VIS_INGAME | VIS_CHEATS));
    }

    #[test]
    fn setting_id_mapping() {
        assert_eq!(SettingId::from_addr(0x4CB3D8), SettingId::SoundVolume);
        assert_eq!(SettingId::from_addr(0x4CB3E8), SettingId::Resolution);
        assert_eq!(SettingId::from_addr(0x4CB3F4), SettingId::FullScreen);
        assert_eq!(SettingId::from_addr(0x4CB404), SettingId::Sensitivity);
        assert_eq!(SettingId::from_addr(0x4CB418), SettingId::Vibration);
        assert!(matches!(SettingId::from_addr(0x1234), SettingId::Other(_)));
    }
}
